M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu22.04.1} date 2024-03-31T18:51:46+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-31T18:51:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.6591Y-2.2299
X5.9709Y-2.2299
M30
